<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // async 异步
        // Generator 函数的语法糖
        //async函数就是将 Generator 函数的星号（*）替换成async，将yield替换成await

        // async函数对 Generator 函数的改进
        // 1. 内置执行器  async函数的执行，与普通函数一模一样，只要一行
        // 2. 更好的语义。async和await，比起星号和yield，语义更清楚了。
        // async表示函数里有异步操async函数的await命令后面，可以是 Promise 对象和原始类型的值（数值、字符串和布尔值，但这时会自动转成立即 resolved 的 Promise 对象）作，await表示紧跟在后面的表达式需要等待结果。
        // 3. async函数的await命令后面，可以是 Promise 对象（大部分）和原始类型的值（数值、字符串和布尔值，但这时会自动转成立即 resolved 的 Promise 对象）。
        // 4. async函数的返回值是 Promise 对象，这比 Generator 函数的返回值是 Iterator 对象方便多了。你可以用then方法指定下一步的操作

        // function fn1() {
        //     return Promise.resolve('success...');
        //     // return Promise.reject('fail...');
        // }
        // // async函数调用完会返回一个promise对象  可直接链式操作
        // // 箭头函数的简写（一个参数 一个语句时）
        // fn1().then(value => console.log(value)).catch(error => console.log(error))


        // await 后面一般为promise对象
        // async function fn2() {
        //     console.log('请求一请求中...');
        //     await request1();

        //     console.log('请求二请求中...');
        //     await request2();

        //     console.log('ending...');
        // }

        // function request1() {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             console.log('请求一成功...');
        //             resolve('success');
        //         }, 1000)
        //     })
        // }

        // function request2() {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             console.log('请求二成功...');
        //             resolve('success');
        //         }, 1000)
        //     })
        // }

        // 内置执行器  async函数的执行，与普通函数一模一样，只要一行
        // fn2();

        //await命令后面的Promise对象，运行结果可能是rejected，所以最好把await命令放在try...catch代码块中
        async function fn3(){
            console.log('start...');
            
            try{
                await request1();
                await fail();
            }catch{
                console.log('error...');
            }
        }

        function fail(){
            return new Promise((resolve,reject)=>{
                reject('error');
            })
        }

        fn3();
    </script>
</body>

</html>